### ISSUE TITLE
Add HPA to helm chart

### ISSUE THREAD

**Issue by AndresPineros** [kube-logging/logging-operator#1082]
**Is your feature request related to a problem? Please describe.**
Add HPA to Helm chart.

**Describe the solution you'd like**
HPA has to be created as an independent resource. Would be easier if it was part of the helm chart.
Currently, the Logging Operator replicas seem to conflict with the HPA. I'm not sure why the documentation shows that they can co-exist, it seems like they can't. Could be easily solved by adding a external variable `externalScaler: true` that tells the operator to stop enforcing the replicas from the Logging resource. Could be solved in fancier ways but this would be the most straight forward to enable the integration.

**Comment by worr** [comment]
I also find myself needing this feature. It's definitely more work than just updating the helm chart to include an hpa resource, since it requires work within the operator so that it does not enforce replica count, like you said.

However, this is definitely becoming a feature that we need, at least on my team. I'd be willing to come up with a diff for the operator, however since it requires CRD changes, I don't want to necessarily dictate the direction that way without input from the maintainers.

**Comment by pepov** [comment]
The operator doesn't mess with the replica count if it's not set explictily:
```
	if r.Logging.Spec.FluentdSpec.Scaling.Replicas > 0 {
		sts.Replicas = util.IntPointer(cast.ToInt32(r.Logging.Spec.FluentdSpec.Scaling.Replicas))
	}
```
https://github.com/kube-logging/logging-operator/blob/master/pkg/resources/fluentd/statefulset.go#L113

Let me know if I'm missing the point.

**Comment by sass1997** [comment]
@worr I'm new in implementing HPA for our components where kube-logging is one part of it. I understand your fear from just adding a HPA and that we should consider also the handling of the operator. As far as I did now my research we could use the operators to scale fluentd for example. I was reading this article https://medium.com/@thescott111/autoscaling-kubernetes-custom-resource-using-the-hpa-957d00bb7993. In this way fluend scaling could be achieved without adapting any operators logic since the hpa is scaling the logging ressource. What do you think?

**Comment by pepov** [comment]
I understand that you can adapt a custom resource to be the primary object for autoscaling, however in our case you can already attach an HPA to the statefulset which is described here:
https://github.com/kube-logging/logging-operator/blob/master/docs/scaling.md

Also the operator supports draining the fluentd nodes when those are scaled down, so you don't have to bother with leftover persistent volumes and the buffer content on them after a scale down event:
https://github.com/kube-logging/logging-operator/blob/master/docs/volume-drainer.md

And as I mentioned above the operator does not mess with replicas if you don't set anything in the fluentd spec.

Let me know if there is a flaw with this approach I don't see.

**Comment by pepov** [comment]
@sass1997 sorry but where is this sentence exactly?

**Comment by sass1997** [comment]
https://github.com/kube-logging/logging-operator/blob/master/docs/scaling.md?plain=1#L42

**Comment by pepov** [comment]
Thanks, I missed that! https://github.com/kube-logging/logging-operator/pull/1710
