### ISSUE TITLE
How to Collect Logs  in  k8s  containerd  ,The format is logfmt

### ISSUE THREAD

**Issue by Allengf** [kube-logging/logging-operator#1216]

**Comment by Allengf** [comment]
How to Collect Logs  in  k8s  containerd  ,The format is logfmt

I use this example, everything is confiscated
https://kube-logging.github.io/docs/examples/loki-nginx/

**Comment by pepov** [comment]
@Allengf what do you mean by "confiscated"?

When the logging operator is deployed a `containerd` based cluster it will automatically detect it and configure fluentbit to use the `cri` parser. The fluentd parser is also configured to use the key "message" instead of "log" which is the major difference between the containerd and the docker log format.

I also don't understand how logfmt comes into the picture.
