### ISSUE TITLE
Skip invalid flows instead of stop processing

### ISSUE THREAD

**Issue by xhejtman** [kube-logging/logging-operator#1567]
**Describe the bug**:

if there is an invalid flow (e.g., with missing output), operator does not generate config at least for valid flows. 
It can lead to DoS, if a user creates such flow, all other users cannot create a new one. I think it should be fixed just to skip invalid flows.

```
{"level":"error","ts":1698751582.322028,"logger":"controller.logging","msg":"Reconciler error","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","name":"rancher-logging-root","namespace":"","error":"failed to build model: referenced clusteroutput not found: ucn","errorVerbose":"referenced clusteroutput not found: ucn\ngithub.com/banzaicloud/logging-operator/pkg/resources/model.FlowForClusterFlow\n\t/workspace/pkg/resources/model/system.go:367\ngithub.com/banzaicloud/logging-operator/pkg/resources/model.CreateSystem\n\t/workspace/pkg/resources/model/system.go:95\ngithub.com/banzaicloud/logging-operator/controllers/logging.(*LoggingReconciler).clusterConfiguration\n\t/workspace/controllers/logging/logging_controller.go:197\ngithub.com/banzaicloud/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/workspace/controllers/logging/logging_controller.go:127\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.
11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nfailed to build model","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
```

rancher/mirrored-banzaicloud-logging-operator:3.17.10

/kind bug

**Comment by pepov** [comment]
One thing you can do instantly is to add a timeout based configcheck, which I beleive should help in more than just this scenario, since it actually starts fluentd instead of executing it with the syntax check flag only:
https://kube-logging.dev/4.4//docs/whats-new/#timeout-based-configuration-checks

In general, if you need stronger isolation the operator provides solutions where flow configurations are segregated into individual aggregators based on namespaces.

It would be recommended in multi-tenant situations, because even if we fix this specific error (invalid output reference), we cannot trivially verify every issue with the flows, for example if one flow consumes all the cpu, etc.

You can do basically two things at the moment:
- Create separate logging resources with disjunct watchNamespaces that refer to your tenant's namespaces, but in this case the fluentbit agents (as many daemonset as many logging resources you have) will collect and send all the logs to each aggregator. If you don't let the user create clusterflow resources they will be able to create flows that refer to their namespaces only so even if the data is there, fluentd will drop everything that is not related to them
- A better solution is to use LoggingRoutes, because using that you can deploy a single fluentbit daemonset which can route logs to specific tenants, so that a tenant won't receive logs from other namespaces

More technical information about LoggingRoutes and multi-tenancy in general:
https://kube-logging.dev/4.4//docs/whats-new/#multitenancy-with-namespace-based-routing

We also have a blog post about this to summarize all aspects with some diagrams involved:
https://axoflow.com/multi-tenancy-using-logging-operator/

Finally don't hesitate to reach out over [Discord](https://discord.gg/UXcKU7GHXT) or the [CNCF Slack channel](https://cloud-native.slack.com/archives/C06DW57NWSJ) if you have further questions!

**Comment by xhejtman** [comment]
Hi, thanks for reply. I a bit hoped that `skipInvalidResources: true` would help here. Isn't it for this case? But I agree that it is far too difficult to find which flow/output is the bad one. My initial issue was purely about operator that stopped processing flows if it found a flow without existing output. In such a case, I asked to skip this flow, but probably the mentioned `skipInvalidResources: true` already does it? Rancher uses stil 3.x version and this was introduced in 4.x version so I missed it.

**Comment by pepov** [comment]
I have to admit I didn't know about that flag and it does exactly what you said.  We can improve the situation a little bit by updating these issues back into the flow status for a better user experience.

**Comment by pepov** [comment]
Closing this as `skipInvalidResources: true` solves this exact issue. @xhejtman have you been able to upgrade? If not let us know over [slack](https://cloud-native.slack.com/archives/C06DW57NWSJ) or [discord](https://discord.gg/UXcKU7GHXT) so that we might be able to help.

**Comment by pepov** [comment]
forgot to follow up: @csabatuz-chess after all are you interested in the multi-tenant approach I was referring here? if yes please let me know!
