### ISSUE TITLE
Logging-Operator User experience Improvement

### ISSUE THREAD

**Issue by sb1975** [kube-logging/logging-operator#413]
My Fluentd instance seems to be in Pending state. $ kubectl get pods -n logging
NAME                                          READY   STATUS        RESTARTS   AGE
grafana-6674455684-v6gq7                      1/1     Terminating   0          4h20m
grafana-6674455684-w96z8                      1/1     Running       0          18m
logging-demo-fluentbit-c5xdn                  1/1     Running       0          172m
logging-demo-fluentbit-q7hs8                  1/1     Running       1          172m
logging-demo-fluentd-0                        0/2     Pending       0          172m

The PVC is pending and PV doesnt seem to be created.
$ kubectl get pvc -A
NAMESPACE   NAME                                                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
logging     logging-demo-fluentd-buffer-logging-demo-fluentd-0   Pending                                                     3h40m

REf Fluentd config : https://etherpad.openstack.org/p/Sudeep

It seems the documentation doesnt call out the complete configuration needed for the Fleuntd in the demo Logging resource - https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/loki-nginx/

It would be helpful to have example code or documentation to experience end-to-end simplest example of logging-operator - otherwise it seems incomplete.

**Comment by matyix** [comment]
As discussed [on Slack](https://community-banzaicloud.slack.com/archives/CGMPPBZBK/p1585061350180000?thread_ts=1584989615.171000&cid=CGMPPBZBK) as well, I am not sure what is the problem here - the quickstart guide so far worked for 99.9% of people, you’ve been the only one with this out of ordinary setup. People appreciate real world examples, instead of `hello-world` type ones on playgrounds with limited capabilities. If PVC was an issue for you, it’s actually the first item in the _Troubleshooting_ guide of how to [switch it off](https://banzaicloud.com/docs/one-eye/logging-operator/troubleshooting/). The closer the examples are to production setups the better for the community. Hope this helps.
